"""add content description column

Revision ID: 386a3de0d706
Revises: 02d46b48e572
Create Date: 2026-08-28 22:40:16.891028

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '386a3de0d706'
down_revision: str | None = '02d46b48e572'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'description')
    # ### end Alembic commands ###
